config_six_region_operate = {
    'model_name': '6_region',
    'ts_first_period': '2017-06-01',
    'ts_last_period': '2017-06-07',
    'run_mode': 'operate',
    'baseload_integer': False,
    'baseload_ramping': False,
    'allow_unmet': True,
    'fixed_caps': {
        'cap_baseload_region1': 20.,
        'cap_peaking_region1': 25.,
        'cap_transmission_region1_region2': 30.,
        'cap_transmission_region1_region5': 20.,
        'cap_transmission_region1_region6': 10.,
        'cap_wind_region2': 40.,
        'cap_solar_region2': 20.,
        'cap_storage_power_region2': 20.,
        'cap_storage_energy_region2': 100.,
        'cap_transmission_region2_region3': 40.,
        'cap_baseload_region3': 50.,
        'cap_peaking_region3': 20.,
        'cap_transmission_region3_region4': 30.,
        'cap_transmission_region4_region5': 30.,
        'cap_wind_region5': 40.,
        'cap_solar_region5': 30.,
        'cap_storage_power_region5': 20.,
        'cap_storage_energy_region5': 100.,
        'cap_transmission_region5_region6': 10.,
        'cap_baseload_region6': 20.,
        'cap_peaking_region6': 20.,
        'cap_wind_region6': 30.,
        'cap_solar_region6': 20.,
        'cap_storage_power_region6': 20.,
        'cap_storage_energy_region6': 100.,
    },
    'extra_override': None,
    'output_save_dir': 'outputs',
    'save_full_model': True,
    'log_level_file': 'DEBUG',  # logging level for log file
    'log_level_stdout': 'INFO',  # logging level for terminal
}